name: KeeleSurvival
version: '${project.version}'
main: dev.joey.keelesurvival.KeeleSurvival
api-version: 1.19
authors: [ Joey ]
depend:
  - Vault
description: A plugin for keele's survival server
website: https://odionwolf.dev
commands:
  pay:
    description: Allows a player to transfer money

  balance:
    description: Allows a player to transfer money
    aliases:
      - bal
      - balance
      - money
      - mon

  eco:
    description: Forces economy
    aliases:
      - economy

  lock:
    description: Locks a chest whilst player is looking
  unlock:
    description: Unlocks a chest whilst player is looking
